#!/bin/bash

version=1.1
lastupdate="2019/09/16" # v1.0
lastupdate="2020/08/03" # v1.1
lastupdate="2020/08/05" # v1.2 add option [-sep]

sep1="^[A-Za-z0-9\*]"
sep2="^\134["
sep3="#  TAG:"
sep="${sep1}"

mylsec() {
  awk -v key="${key}" -v sep="${sep}" 'BEGIN{f=0} \
  {if($0 ~ sep){f++;a[f]=$0}else{a[f]=a[f]"___"$0}}\
  END{for(n in a){if(a[n] ~ key){gsub("___","\n",a[n]);print a[n]}}}'
}

mylsec-v () {
  awk -v key="${key}" -v sep="${sep}" 'BEGIN{f=0} \
  {if($0 ~ sep){f++;a[f]=$0}else{a[f]=a[f]"___"$0}}\
  END{for(n in a){if(a[n] !~ key){gsub("___","\n",a[n]);print a[n]}}}'
}

if [ "$1" == "-sep" ];then
  shift;
  case $1 in
    -1)
      sep="${sep1}"
      shift
      ;;
    -2)
      sep="${sep2}"
      shift
      ;;
    -3)
      sep="${sep3}"
      shift
      ;;
    *)
      sep=$1
      shift
      ;;
  esac
fi

case "$1" in
  -v)
    shift;
    key=$@
    if [ "x$@" == "x" ];then
      mylsec $key
    else
      mylsec-v $key
    fi
    ;;
  -V)
    echo "Version    :lsec ${version}, LastUpdate ${lastupdate}" >&2
    echo "Description:This script is \"section for linux\"" >&2
    echo "Copyright  :Created by labunix" >&2
    exit 0
    ;;
  -h)
    echo "Usage     : $(basename $0) [-sep separate-keyword] [-v|-h] keyword list" >&2
    echo "Version   : $(basename $0) -V" >&2
    exit 1
    ;;
  *)
    key=$@
    mylsec $key
esac
